name: Unit Tests

on:
  push:
    branches:
      - main,test_merge
  pull_request:
    branches: [main,test_merge]

jobs:
  Jest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Run Tests
        run: |
          npm install 
          npm test